Fast data path (weave script only)

diff --git a/weave b/weave
--- a/weave
+++ b/weave
@@ -294,33 +294,57 @@ random_mac() {
 ######################################################################
 
 create_bridge() {
+    BRIDGE_TYPE=
+
     if [ ! -d /sys/class/net/$BRIDGE ] ; then
-        ip link add name $BRIDGE type bridge
-        # Set a random MAC address on the bridge.  Current Linux
-        # kernels already do this when creating a bridge, but there
-        # are rumours it was not always so.
-        ip link set dev $BRIDGE address $(random_mac)
-        # Attempting to set the bridge MTU to a high value directly
-        # fails. Bridges take the lowest MTU of their interfaces. So
-        # instead we create a temporary interface with the desired
-        # MTU, attach that to the bridge, and then remove it again.
-        ip link add name v${CONTAINER_IFNAME}du mtu $MTU type dummy
-        ip link set dev v${CONTAINER_IFNAME}du master $BRIDGE
-        ip link del dev v${CONTAINER_IFNAME}du
-        # Drop traffic from Docker bridge to Weave; it can break subnet isolation
+        # Checking for a specific exit status while set -e is in
+        # effect requires contortions:
+        case $(set +e ; docker run --rm --privileged --net=host $IMAGE --create-datapath --datapath=$BRIDGE ; echo $?) in
+            0)
+                BRIDGE_TYPE=fdp
+                ;;
+
+            17)
+                # Kernel doesn't have ODP
+                BRIDGE_TYPE=bridge
+                ;;
+
+            *)
+                return 1
+                ;;
+        esac
+
+        init_bridge_$BRIDGE_TYPE
+
+        # Drop traffic from Docker bridge to Weave; it can break
+        # subnet isolation
         if [ "$DOCKER_BRIDGE" != "$BRIDGE" ] ; then
             # Note using -I to insert ahead of Docker's bridge rules
             run_iptables -t filter -I FORWARD -i $DOCKER_BRIDGE -o $BRIDGE -j DROP
         fi
+
         # Work around the situation where there are no rules allowing traffic
         # across our bridge. E.g. ufw
         add_iptables_rule filter FORWARD -i $BRIDGE -o $BRIDGE -j ACCEPT
+
         # create a chain for masquerading
         run_iptables -t nat -N WEAVE >/dev/null 2>&1 || true
         add_iptables_rule nat POSTROUTING -j WEAVE
+    else
+        # Detect whether fast datapath is in use on
+        # $BRIDGE. Unfortunately there's no simple way to positively
+        # check whether $BRIDGE is a ODP netdev, so we have to check
+        # whether it is a bridge instead.
+        if [ -d /sys/class/net/$BRIDGE/bridge ] ; then
+            BRIDGE_TYPE=bridge
+        else
+            BRIDGE_TYPE=fdp
+        fi
     fi
 
-    [ "$1" != "--without-ethtool" ] && ethtool -K $BRIDGE tx off >/dev/null
+    if [ "$1" != "--without-ethtool" ] ; then
+        ethtool_tx_off_$BRIDGE_TYPE $BRIDGE
+    fi
 
     ip link set dev $BRIDGE up
 
@@ -329,11 +353,49 @@ create_bridge() {
     configure_arp_cache $BRIDGE
 }
 
+init_bridge_fdp () {
+    # create_bridge already created the datapath netdev
+    ip link set dev $BRIDGE mtu $MTU
+}
+
+init_bridge_bridge () {
+    ip link add name $BRIDGE type bridge
+
+    # Set a random MAC address on the bridge.  Current Linux
+    # kernels already do this when creating a bridge, but there
+    # are rumours it was not always so.
+    ip link set dev $BRIDGE address $(random_mac)
+
+    # Attempting to set the bridge MTU to a high value directly
+    # fails. Bridges take the lowest MTU of their interfaces. So
+    # instead we create a temporary interface with the desired
+    # MTU, attach that to the bridge, and then remove it again.
+    ip link add name v${CONTAINER_IFNAME}du mtu $MTU type dummy
+    ip link set dev v${CONTAINER_IFNAME}du master $BRIDGE
+    ip link del dev v${CONTAINER_IFNAME}du
+}
+
+
+ethtool_tx_off_fdp () {
+    true
+}
+
+ethtool_tx_off_bridge () {
+    $2 ethtool -K $1 tx off >/dev/null
+}
+
 destroy_bridge() {
-    [ -d /sys/class/net/$BRIDGE ] && ip link del dev $BRIDGE
+    if [ -d /sys/class/net/$BRIDGE ] ; then
+        if [ -d /sys/class/net/$BRIDGE/bridge ] ; then
+            ip link del dev $BRIDGE
+        else            docker run --rm --privileged --net=host $IMAGE --delete-datapath --datapath=$BRIDGE
+        fi
+    fi
+
     if [ "$DOCKER_BRIDGE" != "$BRIDGE" ] ; then
         run_iptables -t filter -D FORWARD -i $DOCKER_BRIDGE -o $BRIDGE -j DROP 2>/dev/null || true
     fi
+
     run_iptables -t filter -D FORWARD -i $BRIDGE -o $BRIDGE -j ACCEPT 2>/dev/null || true
     run_iptables -t nat -F WEAVE >/dev/null 2>&1 || true
     run_iptables -t nat -D POSTROUTING -j WEAVE >/dev/null 2>&1 || true
@@ -410,7 +472,7 @@ connect_container_to_bridge() {
     #fi
     ip link add name $LOCAL_IFNAME mtu $MTU type veth peer name $GUEST_IFNAME mtu $MTU || return 1
 
-    if ! ethtool -K $GUEST_IFNAME tx off >/dev/null ||
+    if ! ethtool_tx_off_$BRIDGE_TYPE $GUEST_IFNAME ||
         ! ip link set $GUEST_IFNAME netns $PROCFS/$CONTAINER_PID/ns/net ; then
         # failed before we assigned the veth to the container's
         # namespace
@@ -428,10 +490,18 @@ connect_container_to_bridge() {
     if ! netnsenter ip link set $GUEST_IFNAME down ||
         ! netnsenter ip link set $GUEST_IFNAME name $CONTAINER_IFNAME up ||
         ! ip link set $LOCAL_IFNAME up ||
-        ! ip link set $LOCAL_IFNAME master $BRIDGE ||
+        ! add_iface_$BRIDGE_TYPE $LOCAL_IFNAME ||
         ! configure_arp_cache $CONTAINER_IFNAME "netnsenter" ; then
         return 1
     fi
+}
+
+add_iface_fdp () {
+    docker run --rm --privileged --net=host $IMAGE --datapath=$BRIDGE --add-datapath-iface=$1
+}
+
+add_iface_bridge () {
+    ip link set $1 master $BRIDGE
 }
 
 ask_version() {
@@ -447,6 +517,18 @@ ask_version() {
     [ -n "$DOCKERIMAGE" ] && docker run --rm -e WEAVE_CIDR=none $DOCKERIMAGE $VERSION_COVERAGE_ARGS --version
 }
 
+router_opts_fdp () {
+    if [ -z "$WEAVE_PASSWORD" ] ; then
+        echo "--datapath $BRIDGE"
+    else
+        echo "--datapath $BRIDGE --iface $CONTAINER_IFNAME"
+    fi
+}
+
+router_opts_bridge () {
+    echo "--iface $CONTAINER_IFNAME"
+}
+
 ######################################################################
 # functions invoked through with_container_netns
 ######################################################################
@@ -457,7 +539,7 @@ launch() {
     #    return 1
     #fi
     connect_container_to_bridge &&
-        #netnsenter ethtool -K eth0 tx off >/dev/null &&
+        #ethtool_tx_off_$BRIDGE_TYPE eth0 netnsenter &&
         netnsenter ip link set $CONTAINER_IFNAME up
 }
 
@@ -1115,8 +1197,10 @@ launch_router() {
         --net=host \
         -e WEAVE_PASSWORD \
         -e WEAVE_CIDR=none \
-        $WEAVE_DOCKER_ARGS $IMAGE $COVERAGE_ARGS --iface $CONTAINER_IFNAME --port $CONTAINER_PORT --name "$PEERNAME" --nickname "$(hostname)" --ipalloc-range "$IPRANGE" "$@")
-    with_container_netns_or_die $ROUTER_CONTAINER launch
+        $WEAVE_DOCKER_ARGS $IMAGE $COVERAGE_ARGS $(router_opts_$BRIDGE_TYPE) --port $CONTAINER_PORT --name "$PEERNAME" --nickname "$(hostname)" --ipalloc-range "$IPRANGE" "$@")
+    if [ "$BRIDGE_TYPE" = bridge -o -n "$WEAVE_PASSWORD" ] ; then
+        with_container_netns_or_die $ROUTER_CONTAINER launch
+    fi
     wait_for_status $CONTAINER_NAME $HTTP_PORT
     if [ -n "$IPRANGE" ] ; then
         # Tell the newly-started weave IP allocator about existing weave IPs
